/* 
Retrieve all persons with empty ID_WIKIDATA in T_WC_TMDB_PERSON
when there is a record in T_WC_WIKIDATA_PERSON
and matching ID_IMDB between T_WC_TMDB_PERSON and T_WC_WIKIDATA_PERSON
CSV export of this query is later used for fix of TMDb records using python and Selenium
*/ 
SELECT 
P1.ID_PERSON AS ID_PERSON, 
WP.ID_WIKIDATA AS ID_WIKIDATA, 
WP.ID_IMDB AS ID_IMDB, 
WP.ID_PERSON AS ID_WIKIDATA_PERSON, 
P1.ID_WIKIDATA AS ID_TMDB_WIKIDATA, 
P1.NAME AS NAME, 
P1.ADULT AS ADULT, 
P2.ID_PERSON AS ID_PERSON_ERASE_WIKIDATA_ID 
FROM T_WC_WIKIDATA_PERSON WP 
INNER JOIN T_WC_TMDB_PERSON P1 ON WP.ID_IMDB = P1.ID_IMDB 
LEFT JOIN T_WC_TMDB_PERSON P2 ON WP.ID_WIKIDATA = P2.ID_WIKIDATA 
WHERE WP.ID_IMDB IS NOT NULL AND WP.ID_IMDB <> '' AND WP.ID_IMDB LIKE 'nm%' 
AND WP.ID_WIKIDATA <> P1.ID_WIKIDATA 
AND (P1.ID_WIKIDATA IS NULL OR P1.ID_WIKIDATA = '' OR P1.ID_WIKIDATA NOT REGEXP '^Q[0-9]+$') 
AND WP.ID_WIKIDATA NOT IN ('Q11473776') 
/* 
AND P1.ADULT = 0
 */
ORDER BY P1.ID_PERSON ASC 
