/* 
Retrieve all movies with empty ID_WIKIDATA in T_WC_TMDB_MOVIE
when there is a record in T_WC_WIKIDATA_MOVIE 
and matching ID_IMDB between T_WC_TMDB_MOVIE and T_WC_WIKIDATA_MOVIE
CSV export of this query is later used for fix of TMDb records using python and Selenium
*/ 
SELECT 
M1.ID_MOVIE AS ID_MOVIE, 
WM.ID_WIKIDATA AS ID_WIKIDATA, 
WM.ID_IMDB AS ID_IMDB, 
WM.ID_MOVIE AS ID_WIKIDATA_MOVIE, 
M1.ID_WIKIDATA AS ID_TMDB_WIKIDATA, 
M1.TITLE AS TITLE, 
M1.ADULT AS ADULT, 
M2.ID_MOVIE AS ID_MOVIE_ERASE_WIKIDATA_ID 
FROM T_WC_WIKIDATA_MOVIE WM 
INNER JOIN T_WC_TMDB_MOVIE M1 ON WM.ID_IMDB = M1.ID_IMDB 
LEFT JOIN T_WC_TMDB_MOVIE M2 ON WM.ID_WIKIDATA = M2.ID_WIKIDATA 
WHERE WM.ID_IMDB IS NOT NULL AND WM.ID_IMDB <> '' AND WM.ID_IMDB LIKE 'tt%' 
AND WM.ID_WIKIDATA <> M1.ID_WIKIDATA 
AND (M1.ID_WIKIDATA IS NULL OR M1.ID_WIKIDATA = '' OR M1.ID_WIKIDATA NOT REGEXP '^Q[0-9]+$') 
/* 
AND M1.ADULT = 0
 */
ORDER BY M1.ID_MOVIE ASC 
