/* 
Retrieve all series with empty ID_WIKIDATA in T_WC_TMDB_SERIE
when there is a record in T_WC_WIKIDATA_SERIE 
and matching ID_IMDB between T_WC_TMDB_SERIE and T_WC_WIKIDATA_SERIE
CSV export of this query is later used for fix of TMDb records using python and Selenium
*/ 
SELECT 
S1.ID_SERIE AS ID_SERIE, 
WS.ID_WIKIDATA AS ID_WIKIDATA, 
WS.ID_IMDB AS ID_IMDB, 
WS.ID_SERIE AS ID_WIKIDATA_SERIE, 
S1.ID_WIKIDATA AS ID_TMDB_WIKIDATA, 
S1.TITLE AS TITLE, 
S1.ADULT AS ADULT, 
S2.ID_SERIE AS ID_SERIE_ERASE_WIKIDATA_ID 
FROM T_WC_WIKIDATA_SERIE WS 
INNER JOIN T_WC_TMDB_SERIE S1 ON WS.ID_IMDB = S1.ID_IMDB 
LEFT JOIN T_WC_TMDB_SERIE S2 ON WS.ID_WIKIDATA = S2.ID_WIKIDATA 
WHERE WS.ID_IMDB IS NOT NULL AND WS.ID_IMDB <> '' AND WS.ID_IMDB LIKE 'tt%' 
AND WS.ID_WIKIDATA <> S1.ID_WIKIDATA 
AND (S1.ID_WIKIDATA IS NULL OR S1.ID_WIKIDATA = '' OR S1.ID_WIKIDATA NOT REGEXP '^Q[0-9]+$') 
/* 
AND S1.ADULT = 0
 */
ORDER BY S1.ID_SERIE ASC 
